import {
  CalendarDays,
  ClipboardList,
  LayoutDashboard,
  ListChecks,
  ScrollText,
  ShieldCheck,
  Table2,
  Trophy,
  User,
  Users,
} from "lucide-react";

export const navigationLinks = [
  {
    to: "/dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    showOnDesktop: true,
    showOnMobile: true,
  },
  {
    to: "/my-guesses",
    label: "Meus Palpites",
    mobileLabel: "Palpites",
    icon: ListChecks,
    showOnDesktop: true,
    showOnMobile: true,
  },
  {
    to: "/user-guesses",
    label: "Palpites dos Usuários",
    icon: Users,
    showOnDesktop: true,
    showOnMobile: false,
  },
  {
    to: "/today-games",
    label: "Jogos de Hoje",
    icon: CalendarDays,
    showOnDesktop: true,
    showOnMobile: false,
  },
  {
    to: "/games",
    label: "Todos os Jogos",
    mobileLabel: "Jogos",
    icon: ClipboardList,
    showOnDesktop: true,
    showOnMobile: true,
  },
  {
    to: "/world-cup-table",
    label: "Tabela da Copa",
    icon: Table2,
    showOnDesktop: true,
    showOnMobile: false,
  },
  {
    to: "/results",
    label: "Resultados",
    icon: ShieldCheck,
    showOnDesktop: true,
    showOnMobile: false,
  },
  {
    to: "/ranking",
    label: "Ranking",
    icon: Trophy,
    showOnDesktop: true,
    showOnMobile: true,
  },
  {
    to: "/rules",
    label: "Regras",
    icon: ScrollText,
    showOnDesktop: true,
    showOnMobile: false,
  },
  {
    to: "/profile",
    label: "Perfil",
    icon: User,
    showOnDesktop: true,
    showOnMobile: true,
  },
];
