export const TEAM_NAMES_PT: Record<string, string> = {
  Argentina: "Argentina",
  Australia: "Austrália",
  Austria: "Áustria",
  Belgium: "Bélgica",
  Brazil: "Brasil",
  Canada: "Canadá",
  Chile: "Chile",
  Colombia: "Colômbia",
  Croatia: "Croácia",
  Denmark: "Dinamarca",
  Ecuador: "Equador",
  Egypt: "Egito",
  England: "Inglaterra",
  France: "França",
  Germany: "Alemanha",
  Ghana: "Gana",
  Iran: "Irã",
  Italy: "Itália",
  Japan: "Japão",
  Mexico: "México",
  Morocco: "Marrocos",
  Netherlands: "Holanda",
  Nigeria: "Nigéria",
  Norway: "Noruega",
  Paraguay: "Paraguai",
  Peru: "Peru",
  Poland: "Polônia",
  Portugal: "Portugal",
  Qatar: "Catar",
  "Saudi Arabia": "Arábia Saudita",
  Scotland: "Escócia",
  Senegal: "Senegal",
  Serbia: "Sérvia",
  Spain: "Espanha",
  Sweden: "Suécia",
  Switzerland: "Suíça",
  Tunisia: "Tunísia",
  Turkey: "Turquia",
  Ukraine: "Ucrânia",
  Uruguay: "Uruguai",
  USA: "Estados Unidos",
  Wales: "País de Gales",
};
